utils::globalVariables(
  c("selected_hunterID",
    "has_hunted",
    "has_submitted",
    "prop",
    "sampled_state",
    "tot_prop",
    "ranks",
    "n_y",
    "n_n",
    "sp_group_estimated",
    "has_data",
    "ST",
    "SpeciesGroup",
    "speciesgroup",
    "spp",
    "state_name")
)